<template>
<div class="container pl-10">
    <h1 class="c11" id="h.d8l6niouvxfc"><span class="c5 c4">Solix Privacy Policy</span></h1>
    <p class="c3"><span class="c0">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</span>
    </p>
    <p class="c3"><span class="c0">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. </span>
    </p>
    <h1 class="c3" id="h.9ue6v1d7kqw"><span class="c5 c4">Interpretation and Definitions</span></h1>
    <h2 class="c3" id="h.sh6pycdyde0l"><span class="c5 c4">Interpretation</span></h2>
    <p class="c3"><span class="c0">The words of which the initial letter is capitalized have meanings defined under the following conditions.</span>
    </p>
    <p class="c3"><span class="c0">The following definitions shall have the same meaning regardless of whether they appear in singular or plural.</span>
    </p>
    <h2 class="c3" id="h.vqbg4sfh8hfw"><span class="c4 c5">Definitions</span></h2>
    <p class="c3"><span class="c0">For the purposes of this Privacy Policy:</span></p>
    <ul class="c2 lst-kix_z0uh8usi7395-0 start">
        <li class="c1 li-bullet-0"><span class="c4">You</span><span class="c0">&nbsp;mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Company</span><span>&nbsp;(referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Solix, (</span><span
            class="c4">paste address here</span><span class="c0">).</span></li>
        <li class="c1 li-bullet-0"><span class="c4">Affiliate</span><span class="c0">&nbsp;means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Account</span><span class="c0">&nbsp;means a unique account created for You to access our Service or parts of our Service.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Website</span><span class="c0">&nbsp;refers to Solix, accessible from solix.com</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Service</span><span class="c0">&nbsp;refers to the Website.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Country</span><span
            class="c0">&nbsp;refers to: Republic of Moldova</span></li>
        <li class="c1 li-bullet-0"><span class="c4">Service Provider</span><span class="c0">&nbsp;means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Third-party Social Media Service</span><span class="c0">&nbsp;refers to any website or any social network website through which a User can log in or create an account to use the Service.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Personal Data</span><span class="c0">&nbsp;is any information that relates to an identified or identifiable individual.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Cookies</span><span class="c0">&nbsp;are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Device</span><span class="c0">&nbsp;means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Usage Data</span><span class="c0">&nbsp;refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</span>
        </li>
    </ul>
    <p class="c9"><span class="c4 c6">Collecting and Using Your Personal Data</span></p>
    <p class="c9"><span class="c5 c4">Types of Data Collected</span></p>
    <h3 class="c12" id="h.wworu6wvplzw"><span class="c5 c4">Personal Data</span></h3>
    <p class="c3"><span class="c0">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</span>
    </p>
    <ul class="c2 lst-kix_aupxpop7jwda-0 start">
        <li class="c1 li-bullet-0"><span class="c0">Email address</span></li>
        <li class="c1 li-bullet-0"><span class="c0">First name and last name</span></li>
        <li class="c1 li-bullet-0"><span class="c0">Phone number</span></li>
        <li class="c1 li-bullet-0"><span class="c0">Address, State, Province, ZIP/Postal code, City</span></li>
        <li class="c1 li-bullet-0"><span class="c0">Usage Data</span></li>
    </ul>
    <h3 class="c3" id="h.1s415qqgwt4y"><span class="c5 c4">Usage Data</span></h3>
    <p class="c3"><span class="c0">Usage Data is collected automatically when using the Service.</span></p>
    <p class="c3"><span class="c0">Usage Data may include information such as Your Device&#39;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</span>
    </p>
    <p class="c3"><span class="c0">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</span>
    </p>
    <p class="c3"><span class="c0">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</span>
    </p>
    <h3 class="c3" id="h.ccyj7umrp47p"><span class="c5 c4">Tracking Technologies and Cookies</span></h3>
    <p class="c3"><span class="c0">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</span>
    </p>
    <p class="c3"><span class="c0">You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</span>
    </p>
    <p class="c3"><span>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser. Learn more about cookies here: </span><span><a
        class="c13"
        href="https://www.google.com/url?q=https://www.freeprivacypolicy.com/blog/cookies/&amp;sa=D&amp;source=editors&amp;ust=1618324327203000&amp;usg=AOvVaw3bFykgXbQZ-f3iReFnGfQf">Cookies: What Do They Do?</a></span>
    </p>
    <p class="c3"><span class="c0">We use both session and persistent Cookies for the purposes set out below:</span></p>
    <ul class="c2 lst-kix_50m34c9x8hvi-0 start">
        <li class="c1 li-bullet-0"><span class="c4">Necessary / Essential Cookies<br></span><span class="c0">Type: Session Cookies<br>Administered by: Us<br>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Cookies Policy / Notice Acceptance Cookies<br></span><span
            class="c0">Type: Persistent Cookies<br>Administered by: Us<br>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">Functionality Cookies<br></span><span class="c0">Type: Persistent Cookies<br>Administered by: Us<br>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</span>
        </li>
    </ul>
    <p class="c3"><span class="c0">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy.</span>
    </p>
    <h2 class="c3" id="h.czxxu9g6rqal"><span class="c5 c4">Use of Your Personal Data</span></h2>
    <p class="c3"><span class="c0">The Company may use Personal Data for the following purposes:</span></p>
    <ul class="c2 lst-kix_8uhgxxhcu1q-0 start">
        <li class="c1 li-bullet-0"><span class="c4">To provide and maintain our Service</span><span class="c0">, including to monitor the usage of our Service.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">To manage Your Account:</span><span class="c0">&nbsp;to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">For the performance of a contract:</span><span class="c0">&nbsp;the development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or of any other contract with Us through the Service.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">To contact You:</span><span class="c0">&nbsp;To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&#39;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">To provide You</span><span class="c0">&nbsp;with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">To manage Your requests:</span><span class="c0">&nbsp;To attend and manage Your requests to Us.</span>
        </li>
    </ul>
    <p class="c3"><span class="c0">We may share your personal information in the following situations:</span></p>
    <ul class="c2 lst-kix_uacuk91qs4nj-0 start">
        <li class="c1 li-bullet-0"><span class="c4">With Service Providers:</span><span class="c0">&nbsp;We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">For Business transfers:</span><span class="c0">&nbsp;We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">With Affiliates:</span><span class="c0">&nbsp;We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners, or other companies that We control or that are under common control with Us.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">With Business Partners:</span><span class="c0">&nbsp;We may share Your information with Our business partners to offer You certain products, services, or promotions.</span>
        </li>
        <li class="c1 li-bullet-0"><span class="c4">With other users:</span><span class="c0">&nbsp;when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures, and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</span>
        </li>
    </ul>
    <h2 class="c3" id="h.1bz15ezg2a2c"><span class="c5 c4">Retention of Your Personal Data</span></h2>
    <p class="c3"><span class="c0">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</span>
    </p>
    <p class="c3"><span class="c0">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer periods.</span>
    </p>
    <h2 class="c3" id="h.1eggrh6hl2qx"><span class="c5 c4">Transfer of Your Personal Data</span></h2>
    <p class="c3"><span class="c0">Your information, including Personal Data, is processed at the Company&#39;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to &mdash; and maintained on &mdash; computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</span>
    </p>
    <p class="c3"><span class="c0">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</span>
    </p>
    <p class="c3"><span class="c0">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</span>
    </p>
    <h2 class="c3" id="h.lx3magy94q0j"><span class="c5 c4">Disclosure of Your Personal Data</span></h2>
    <h3 class="c3" id="h.jud0hx1jh33z"><span class="c5 c4">Business Transactions</span></h3>
    <p class="c3"><span class="c0">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</span>
    </p>
    <h3 class="c3" id="h.ko6448705vn"><span class="c5 c4">Law enforcement</span></h3>
    <p class="c3"><span class="c0">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</span>
    </p>
    <h3 class="c3" id="h.jrxn687jgzuj"><span class="c5 c4">Other legal requirements</span></h3>
    <p class="c3"><span class="c0">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</span>
    </p>
    <ul class="c2 lst-kix_gzc0fzfxpi99-0 start">
        <li class="c1 li-bullet-0"><span class="c0">Comply with a legal obligation</span></li>
        <li class="c1 li-bullet-0"><span class="c0">Protect and defend the rights or property of the Company</span></li>
        <li class="c1 li-bullet-0"><span class="c0">Prevent or investigate possible wrongdoing in connection with the Service</span>
        </li>
        <li class="c1 li-bullet-0"><span
            class="c0">Protect the personal safety of Users of the Service or the public</span></li>
        <li class="c1 li-bullet-0"><span class="c0">Protect against legal liability</span></li>
    </ul>
    <h2 class="c3" id="h.tv5pa8ty2vdz"><span class="c5 c4">Security of Your Personal Data</span></h2>
    <p class="c3"><span>Solix</span><span class="c0">&nbsp;will use reasonable technical, administrative, and physical measures to protect information contained in our system against misuse, loss or alteration. All information you provide to us is stored on our secure servers or secured servers licensed for use by us. Solix complies with the Payment Card Industry Data Security Standard (PCI-DSS).</span>
    </p>
    <p class="c3"><span class="c0">Where we have given you (or where you have chosen) a password that enables you to access certain parts of our Processing Services or to engage with our customer service team, you are responsible for keeping this password confidential and adequately complex. We ask you not to share a password with anyone and change your password every 90 days. If we receive instructions using your log-in information we will consider that you have authorized the instructions.</span>
    </p>
    <p class="c3 c8"><span class="c0"></span></p>
    <p class="c3"><span class="c0">Unfortunately, the transmission of information via the Internet is not completely secure. Although we will do our best to protect your Personal data, we cannot guarantee the security of your data transmitted to our Website; any transmission is at your own risk.</span>
    </p>
    <p class="c3"><span class="c0">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</span>
    </p>
    <h1 class="c3" id="h.yqudp7qrxef"><span class="c5 c4">Children&#39;s Privacy</span></h1>
    <p class="c3"><span class="c0">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please Contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</span>
    </p>
    <p class="c3"><span class="c0">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&#39;s consent before We collect and use that information.</span>
    </p>
    <h1 class="c3" id="h.vld6wtv2pwe1"><span class="c5 c4">Links to Other Websites</span></h1>
    <p class="c3"><span class="c0">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&#39;s site. We strongly advise You to review the Privacy Policy of every site You visit.</span>
    </p>
    <p class="c3"><span class="c0">We have no control over and assume no responsibility for the content, privacy policies, or practices of any third party sites or services.</span>
    </p>
    <h1 class="c3" id="h.o7mzlfci3lew"><span class="c5 c4">Changes to this Privacy Policy</span></h1>
    <p class="c3"><span class="c0">We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</span>
    </p>
    <p class="c3"><span class="c0">We will let You know via email and/or a prominent notice on Our Service, before the change becomes effective and update the &quot;Last Updated&quot; date at the top of this Privacy Policy.</span>
    </p>
    <p class="c3"><span class="c0">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</span>
    </p>
    <h2 class="c7" id="h.1r5njh7qqxd0"><span class="c0">The conflict between this Privacy Policy and the Terms of Service or the Website Terms and conditions</span>
    </h2>
    <p class="c14 c15"><span class="c0">Where there is a conflict between this Privacy Policy and an explicit provision of the Terms of Service or the Website Terms related to our Processing Services, this Privacy Policy will prevail over those other Terms.</span>
    </p>
    <h2 class="c3" id="h.r1i4nc2vvugb"><span class="c0">Contact Us</span></h2>
    <p class="c3"><span class="c0">If you have any questions about this Privacy Policy, You can contact us by email: info@solix.md</span>
    </p>
    <p class="c8 c14"><span class="c0"></span></p>
    <p class="c8 c16"><span class="c0"></span></p>
</div>
</template>

<script>
    import {bus} from "../../../event/eventbus";

    export default {
        name: 'privacy',
        data() {
            return {}
        },
        mounted() {
            bus.$emit('position','relative');
            bus.$emit('theme','light')
        }
    }
</script>
<style scoped>
    h2{
        font-size: 24px !important;
        line-height: 65px;
    }
    h3{
        font-size: 18px !important;
        line-height: 65px;
    }
    h1{
        font-size: 30px !important;
        line-height: 65px;
    }
    p{
        font-size: 14px !important;
    }
</style>
